# Generated by Django 4.2.21 on 2025-08-03 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('finished', 'Finished')], default='not-started', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('system', models.CharField(choices=[('league', 'League'), ('groups_elimination', 'Groups + Elimination'), ('elimination', 'Elimination Only')], max_length=30)),
                ('image', models.ImageField(upload_to='competitions/')),
                ('min_members_per_team', models.IntegerField()),
                ('max_members_per_team', models.IntegerField(default=1)),
                ('teams_per_group', models.IntegerField(blank=True, null=True)),
                ('teams_qualified_per_group', models.IntegerField(blank=True, null=True)),
                ('group_elimination_phase', models.CharField(blank=True, choices=[('groups', 'Fase de Grupos'), ('knockout', 'Fase Eliminatória'), ('finished', 'Finalizada')], default='groups', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
            options={
                'unique_together': {('team_id', 'competition')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Modalidade',
                'verbose_name_plural': 'Modalidades',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_match_number', models.IntegerField()),
                ('status', models.CharField(choices=[('not-started', 'Não iniciado'), ('in-progress', 'Em andamento'), ('finished', 'Finalizado')], default='not-started', max_length=20)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('score_home', models.IntegerField(blank=True, null=True)),
                ('score_away', models.IntegerField(blank=True, null=True)),
                ('away_feeder_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_away_team', to='competitions.match')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.group')),
                ('home_feeder_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_home_team', to='competitions.match')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.round')),
                ('team_away', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='competitions.competitionteam')),
                ('team_home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='competitions.competitionteam')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.competitionteam')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.modality'),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('points', models.IntegerField()),
                ('games_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('score_pro', models.IntegerField()),
                ('score_against', models.IntegerField()),
                ('score_difference', models.IntegerField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionteam')),
            ],
        ),
    ]
