# Generated by Django 4.2.21 on 2025-07-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_feeder_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_away_team', to='competitions.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_feeder_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeds_home_team', to='competitions.match'),
        ),
    ]
