# Generated by Django 4.2.21 on 2025-07-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_match_away_feeder_match_match_home_feeder_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='competitions.competitionteam'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='competitions.competitionteam'),
        ),
    ]
